name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  quality-gates:
    name: Quality gates on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        shell: bash
        run: deno check src/**/*.ts

  unit-tests:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run unit tests with coverage
        run: deno test --allow-all --coverage=cov_profile tests/unit/

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov_profile.lcov
          flags: unit-tests
          fail_ci_if_error: false

  integration-tests:
    name: Integration tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run integration tests with coverage
        run: deno test --allow-all --coverage=cov_profile tests/integration/

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov_profile.lcov
          flags: integration-tests
          fail_ci_if_error: false

  distribution-tests:
    name: Distribution tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Build Deno binary
        run: deno task compile

      - name: Build npm package
        run: deno task npm:build

      - name: Run distribution tests with coverage
        run: deno test --allow-all --coverage=cov_profile tests/distribution/

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov_profile.lcov
          flags: distribution-tests
          fail_ci_if_error: false

  ci-tests:
    name: CI tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Build Deno binary
        run: deno task compile

      - name: Build npm package
        run: deno task npm:build

      - name: Run CI tests with coverage
        run: deno test --allow-all --coverage=cov_profile tests/ci/

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov_profile.lcov
          flags: ci-tests
          fail_ci_if_error: false

  build:
    name: Build binaries and npm package
    runs-on: ubuntu-latest
    needs: [quality-gates, unit-tests, integration-tests, distribution-tests, ci-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Deno binary
        run: deno task compile

      - name: Build npm package
        run: deno task npm:build

      - name: Test npm package
        run: |
          cd npm
          npm install
          node dist/main.js --help
